In [1]:
import numpy as np

# 建立增廣矩陣 [A|b]
A = np.array([
    [1.19, 2.11, -100, 1, 1.12],
    [14.2, -0.112, 12.2, -1, 3.44],
    [0, 100, -99.9, 1, 2.15],
    [15.3, 0.110, -13.1, -1, 4.16]
], dtype=float)

n = len(A)

# Gaussian elimination with partial pivoting
for i in range(n):
    # Pivoting: find the row with the max value in current column
    max_row = i + np.argmax(np.abs(A[i:, i]))
    if i != max_row:
        A[[i, max_row]] = A[[max_row, i]]  # swap rows

    # Eliminate entries below the pivot
    for j in range(i + 1, n):
        factor = A[j][i] / A[i][i]
        A[j, i:] -= factor * A[i, i:]

# Back substitution
x = np.zeros(n)
for i in range(n - 1, -1, -1):
    x[i] = (A[i, -1] - np.dot(A[i, i+1:n], x[i+1:n])) / A[i, i]

print("Solution: ", x)


Solution:  [ 0.17677633  0.0126921  -0.0206612  -1.18326429]


In [3]:
import numpy as np

# 定義矩陣 A
A = np.array([
    [4, 1, -1, 0],
    [1, 3, -1, 0],
    [-1, -1, 6, 2],
    [0, 0, 2, 5]
], dtype=float)

# 計算反矩陣
A_inv = np.linalg.inv(A)

# 顯示結果
print("Inverse of A:")
print(A_inv)


Inverse of A:
[[ 0.27969349 -0.08045977  0.03831418 -0.01532567]
 [-0.08045977  0.37931034  0.05747126 -0.02298851]
 [ 0.03831418  0.05747126  0.21072797 -0.08429119]
 [-0.01532567 -0.02298851 -0.08429119  0.23371648]]


In [6]:
import numpy as np

# 定義 A 和 b
A = np.array([
    [3, -1,  0,  0],
    [-1, 3, -1,  0],
    [0, -1, 3, -1],
    [0,  0, -1, 3]
], dtype=float)

b = np.array([2, 3, 4, 1], dtype=float)

n = len(b)
L = np.zeros((n, n))
U = np.identity(n)  # Crout: U has 1's on the diagonal

# Crout Factorization
for j in range(n):
    for i in range(j, n):
        L[i][j] = A[i][j] - sum(L[i][k] * U[k][j] for k in range(j))
    for i in range(j+1, n):
        U[j][i] = (A[j][i] - sum(L[j][k] * U[k][i] for k in range(j))) / L[j][j]

# Forward substitution to solve L*y = b
y = np.zeros(n)
for i in range(n):
    y[i] = (b[i] - sum(L[i][j] * y[j] for j in range(i))) / L[i][i]

# Back substitution to solve U*x = y
x = np.zeros(n)
for i in range(n-1, -1, -1):
    x[i] = y[i] - sum(U[i][j] * x[j] for j in range(i+1, n))

print("Solution x:", x)


Solution x: [1.43636364 2.30909091 2.49090909 1.16363636]
